    // ============ SHARED DATA ============
    const RANKS = ['A','K','Q','J','T','9','8','7','6','5','4','3','2'];
    const SUITS = [{s:'♠',c:'black'},{s:'♥',c:'red'},{s:'♦',c:'red'},{s:'♣',c:'black'}];
    const POSITIONS = ['UTG','MP','CO','BTN','SB','BB'];
    const POS_ALIAS = {'utg':'UTG','u':'UTG','mp':'MP','m':'MP','co':'CO','c':'CO','btn':'BTN','b':'BTN','bu':'BTN','sb':'SB','bb':'BB'};

    const OPEN_RANGES = {
        UTG:{raise:['AA','KK','QQ','JJ','TT','AKs','AQs','AJs','ATs','KQs','KJs','QJs','AKo','AQo'],call:['99','88','77','A9s','A8s','A5s','A4s','A3s','A2s','KTs','QTs','JTs','T9s','98s','AJo']},
        MP:{raise:['AA','KK','QQ','JJ','TT','99','AKs','AQs','AJs','ATs','A9s','KQs','KJs','KTs','QJs','QTs','JTs','AKo','AQo','AJo','KQo'],call:['88','77','66','A8s','A7s','A5s','A4s','A3s','A2s','T9s','98s','87s','ATo','KJo']},
        CO:{raise:['AA','KK','QQ','JJ','TT','99','88','77','AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KQs','KJs','KTs','K9s','QJs','QTs','Q9s','JTs','J9s','T9s','98s','87s','AKo','AQo','AJo','ATo','KQo','KJo','QJo'],call:['66','55','76s','65s','KTo','QTo','JTo','A9o']},
        BTN:{raise:['AA','KK','QQ','JJ','TT','99','88','77','66','55','44','AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','QJs','QTs','Q9s','Q8s','JTs','J9s','J8s','T9s','T8s','98s','97s','87s','86s','76s','75s','65s','64s','54s','AKo','AQo','AJo','ATo','A9o','A8o','A7o','KQo','KJo','KTo','K9o','QJo','QTo','Q9o','JTo','J9o','T9o'],call:['33','22','K4s','K3s','K2s','Q7s','Q6s','J7s','T7s','96s','85s','53s','43s','A6o','A5o','A4o','A3o','A2o','K8o','Q8o','J8o','T8o','98o']},
        SB:{raise:['AA','KK','QQ','JJ','TT','99','88','77','66','AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KQs','KJs','KTs','K9s','K8s','QJs','QTs','Q9s','JTs','J9s','T9s','98s','87s','76s','AKo','AQo','AJo','ATo','A9o','KQo','KJo','KTo','QJo','QTo','JTo'],call:['55','44','33','K7s','K6s','K5s','Q8s','J8s','T8s','97s','86s','75s','65s','54s','A8o','A7o','K9o','Q9o','J9o','T9o']},
        BB:{raise:['AA','KK','QQ','JJ','TT','99','AKs','AQs','AJs','ATs','KQs','KJs','AKo','AQo'],call:['88','77','66','55','44','33','22','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KTs','K9s','K8s','K7s','K6s','K5s','QJs','QTs','Q9s','Q8s','Q7s','JTs','J9s','J8s','J7s','T9s','T8s','T7s','98s','97s','96s','87s','86s','76s','75s','65s','64s','54s','53s','43s','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o','A3o','A2o','KQo','KJo','KTo','K9o','K8o','QJo','QTo','Q9o','JTo','J9o','T9o','98o','87o']}
    };
    const VS_RAISE = {
        UTG:{raise:['AA','KK','QQ','AKs'],call:['JJ','TT','99','AQs','AJs','AKo','KQs']},
        MP:{raise:['AA','KK','QQ','AKs','AKo'],call:['JJ','TT','99','88','AQs','AJs','ATs','KQs','AQo']},
        CO:{raise:['AA','KK','QQ','JJ','AKs','AKo','AQs'],call:['TT','99','88','77','AJs','ATs','KQs','KJs','QJs','AQo','AJo','KQo']},
        BTN:{raise:['AA','KK','QQ','JJ','TT','AKs','AQs','AKo'],call:['99','88','77','66','AJs','ATs','A9s','A5s','KQs','KJs','KTs','QJs','QTs','JTs','T9s','98s','AQo','AJo','KQo','KJo']},
        SB:{raise:['AA','KK','QQ','JJ','AKs','AQs','AKo'],call:['TT','99','88','77','AJs','ATs','KQs','KJs','QJs','JTs','AQo','AJo','KQo']},
        BB:{raise:['AA','KK','QQ','JJ','TT','AKs','AQs','AKo'],call:['99','88','77','66','55','44','33','22','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KQs','KJs','KTs','K9s','QJs','QTs','Q9s','JTs','J9s','T9s','98s','87s','76s','65s','AQo','AJo','ATo','KQo','KJo','QJo','JTo']}
    };

    const HAND_RANKINGS = [
        'Royal Flush','Straight Flush','Four of a Kind','Full House','Flush',
        'Straight','Three of a Kind','Two Pair','One Pair','High Card'
    ];

    const GLOSSARY = [
        {name:'올인 (All-in)',desc:'가진 칩 전부를 베팅하는 것'},
        {name:'앤티 (Ante)',desc:'모든 플레이어가 매 핸드 시작 전에 내는 강제 베팅 (토너먼트)'},
        {name:'아웃츠 (Outs)',desc:'내 핸드를 이길 수 있는 핸드로 만들어줄 남은 카드 수'},
        {name:'오픈 (Open)',desc:'누구도 베팅하지 않은 상태에서 첫 레이즈'},
        {name:'오버카드 (Overcard)',desc:'보드의 가장 높은 카드보다 높은 내 홀카드'},
        {name:'오프수트 (Offsuit)',desc:'두 카드의 무늬가 다른 것'},
        {name:'벨류벳 (Value Bet)',desc:'상대가 약한 핸드로 콜해줄 것을 기대하고 하는 베팅'},
        {name:'바이인 (Buy-in)',desc:'게임에 참가하기 위해 필요한 금액'},
        {name:'뱅크롤 (Bankroll)',desc:'포커에 사용할 수 있는 총 자금'},
        {name:'버튼 (Button)',desc:'딜러 위치. 프리플랍 마지막 행동, 플랍 이후 마지막 행동'},
        {name:'블라인드 (Blind)',desc:'강제 베팅. SB와 BB가 카드 받기 전에 냄'},
        {name:'블러프 (Bluff)',desc:'약한 핸드로 강한 척 베팅해서 상대를 폴드시키는 것'},
        {name:'블로커 (Blocker)',desc:'상대가 특정 핸드를 가질 확률을 줄이는 내 카드'},
        {name:'보드 (Board)',desc:'테이블에 깔린 커뮤니티 카드 (플랍+턴+리버)'},
        {name:'브로드웨이 (Broadway)',desc:'T, J, Q, K, A 카드. 또는 이들로 만든 스트레이트'},
        {name:'셋 (Set)',desc:'포켓 페어 + 보드 1장으로 만든 트리플'},
        {name:'셋마이닝 (Set Mining)',desc:'셋을 맞추기 위해 포켓 페어로 콜하는 전략'},
        {name:'세미블러프 (Semi-bluff)',desc:'드로우가 있는 상태에서 블러프 베팅 (맞으면 이기고, 상대 폴드시켜도 이김)'},
        {name:'수티드 (Suited)',desc:'두 카드의 무늬가 같은 것'},
        {name:'수티드 커넥터 (Suited Connector)',desc:'같은 무늬의 연속된 카드 (예: 8♥9♥)'},
        {name:'스트래들 (Straddle)',desc:'BB 왼쪽 자리가 자발적으로 2BB를 내는 블라인드 형태의 베팅'},
        {name:'스택 (Stack)',desc:'내가 가진 칩의 총량'},
        {name:'스틸 (Steal)',desc:'블라인드를 뺏기 위한 레이트 포지션 레이즈'},
        {name:'슬로우플레이 (Slowplay)',desc:'강한 핸드를 가지고 약하게 플레이해 상대를 낚는 것'},
        {name:'C-bet (컨티뉴에이션 벳)',desc:'프리플랍 레이저가 플랍에서도 이어서 베팅하는 것'},
        {name:'체크레이즈 (Check-raise)',desc:'먼저 체크한 뒤 상대가 베팅하면 레이즈하는 것'},
        {name:'커넥터 (Connector)',desc:'연속된 숫자의 두 카드 (예: 78, JT)'},
        {name:'콜드콜 (Cold Call)',desc:'레이즈와 리레이즈가 있는 상황에서 처음 참여하며 콜'},
        {name:'킥커 (Kicker)',desc:'같은 페어일 때 승부를 결정하는 나머지 카드'},
        {name:'타이트 (Tight)',desc:'적은 수의 핸드만 플레이하는 스타일'},
        {name:'턴 (Turn)',desc:'네 번째 커뮤니티 카드'},
        {name:'텔 (Tell)',desc:'상대의 핸드를 추측할 수 있게 해주는 행동/습관'},
        {name:'틸트 (Tilt)',desc:'감정적으로 흔들려 비이성적인 플레이를 하는 것'},
        {name:'트리플 (Three of a Kind)',desc:'같은 숫자 3장'},
        {name:'드로우 (Draw)',desc:'아직 완성되지 않았지만 카드 한두 장으로 완성 가능한 핸드'},
        {name:'도미네이트 (Dominate)',desc:'상대 핸드와 카드 하나가 겹치면서 키커가 앞서는 상황 (예: AK vs AJ)'},
        {name:'넛츠 (Nuts)',desc:'현재 보드에서 가능한 최강 핸드'},
        {name:'니트 (Nit)',desc:'극도로 타이트한 플레이어'},
        {name:'GTO',desc:'Game Theory Optimal. 상대가 어떻게 플레이하든 착취당하지 않는 전략'},
        {name:'ICM',desc:'Independent Chip Model. 토너먼트에서 칩의 실제 가치를 계산하는 모델'},
        {name:'팟 (Pot)',desc:'현재 핸드에 베팅된 총 금액'},
        {name:'팟 오즈 (Pot Odds)',desc:'콜 비용 대비 팟 크기의 비율. 콜의 수학적 가치 판단'},
        {name:'포지션 (Position)',desc:'행동 순서에서의 위치. 뒤에서 행동할수록 유리'},
        {name:'프리미엄 핸드 (Premium)',desc:'AA, KK, QQ, AK 등 최상위 핸드'},
        {name:'프리플랍 (Preflop)',desc:'홀카드 2장만 받은 첫 베팅 라운드'},
        {name:'플랍 (Flop)',desc:'커뮤니티 카드 3장이 동시에 깔리는 두 번째 라운드'},
        {name:'플러시 드로우 (Flush Draw)',desc:'같은 무늬 4장이 있어서 1장 더 오면 플러시 완성'},
        {name:'폴드 에퀴티 (Fold Equity)',desc:'베팅으로 상대를 폴드시킬 수 있는 추가 가치'},
        {name:'핏 오어 폴드 (Fit or Fold)',desc:'플랍에서 맞으면 계속, 안 맞으면 포기하는 전략'},
        {name:'핸드 레인지 (Hand Range)',desc:'특정 상황에서 플레이할 수 있는 핸드의 범위'},
        {name:'홀카드 (Hole Cards)',desc:'나만 볼 수 있는 2장의 카드'},
        {name:'EV (Expected Value)',desc:'기대값. 장기적으로 특정 플레이의 평균 수익/손실'},
        {name:'3-벳 (3-bet)',desc:'상대 레이즈에 대한 리레이즈'},
        {name:'4-벳 (4-bet)',desc:'3-벳에 대한 리레이즈'},
        {name:'림프 (Limp)',desc:'프리플랍에서 레이즈 없이 빅블라인드만 콜하는 것'},
        {name:'리버 (River)',desc:'다섯 번째이자 마지막 커뮤니티 카드'},
        {name:'리버스 임플라이드 오즈',desc:'내 드로우가 완성되어도 상대가 더 좋은 핸드를 가진 경우 잃을 추가 금액'},
        {name:'루즈 (Loose)',desc:'많은 핸드를 플레이하는 스타일'},
        {name:'랙 (Lag)',desc:'Loose-Aggressive. 넓은 범위를 공격적으로 플레이'},
        {name:'임플라이드 오즈 (Implied Odds)',desc:'현재 팟 + 앞으로 더 딸 수 있는 금액을 포함한 오즈'},
        {name:'에퀴티 (Equity)',desc:'현재 핸드가 팟에서 차지하는 기대 지분'},
        {name:'오버벳 (Overbet)',desc:'팟보다 큰 금액을 베팅하는 것'},
        {name:'언더벳 (Underbet)',desc:'팟 대비 매우 작은 금액을 베팅하는 것'},
        {name:'배럴 (Barrel)',desc:'연속적인 베팅. 더블배럴 = 플랍+턴 베팅, 트리플배럴 = 플랍+턴+리버 베팅'},
        {name:'팟 컨트롤 (Pot Control)',desc:'중간 강도 핸드로 팟이 너무 커지지 않게 조절하는 것'},
        {name:'멀티웨이 (Multiway)',desc:'3명 이상의 플레이어가 팟에 참여한 상황'},
        {name:'헤즈업 (Heads-up)',desc:'두 명만 남은 상황'},
        {name:'레귤러 (Regular)',desc:'그 스테이크에서 주로 플레이하는 숙련 플레이어'},
        {name:'피쉬 (Fish)',desc:'실력이 부족한 플레이어 (비하 표현)'},
        {name:'분산 (Variance)',desc:'단기적 운의 영향. 실력과 무관한 결과 변동'},
        {name:'거트샷 (Gutshot)',desc:'가운데 한 장이 필요한 스트레이트 드로우 (아웃츠 4개)'},
        {name:'오픈엔드 (Open-ended)',desc:'양쪽 끝 카드로 완성 가능한 스트레이트 드로우 (아웃츠 8개)'},
        {name:'트립스 (Trips)',desc:'보드 페어 + 핸드 1장으로 만든 트리플 (셋과 구분)'},
        {name:'동크 벳 (Donk Bet)',desc:'오리지널 레이저가 아닌 플레이어가 먼저 베팅하는 것'},
        {name:'쇼다운 (Showdown)',desc:'리버 액션 까지 끝나고 핸드를 공개해 승자를 가리는 것'},
        {name:'드로잉 데드 (Drawing Dead)',desc:'어떤 카드가 와도 이길 수 없는 상태'},
        {name:'히어로 콜 (Hero Call)',desc:'비이성적 약한 핸드로 상대방의 블러프를 잡아내는 콜'},
        {name:'오리지널 (Original)',desc:'프리플랍에서 베팅을 먼저 했던 플레이어'},
        {name:'머크 (Muck)',desc:'카드를 보여주지 않고 폴드하는 것. 쇼다운에서 핸드를 공개하지 않고 포기'},
        {name:'프리즈 아웃 (Freeze Out)',desc:'한번 아웃되면 재참가가 불가능한 토너먼트 형식'},
        {name:'TPTK (Top Pair Top Kicker)',desc:'보드 최고 카드와 페어 + 최고 키커 (예: AK으로 K 보드에서)'},
        {name:'VPIP',desc:'Voluntarily Put Money In Pot. 자발적으로 팟에 참여하는 비율'},
        {name:'패시브 플레이어 (Passive Player)',desc:'콜 위주의 수비적인 플레이를 하는 사람'},
        {name:'어그레시브 플레이어 (Aggressive Player)',desc:'베팅과 레이즈 위주의 공격적 플레이를 하는 사람'},
        {name:'버블 (Bubble)',desc:'토너먼트에서 상금권 직전의 등수 자리'},
        {name:'애드온 (Add-on)',desc:'토너먼트에서 추가로 더 많은 칩을 사기'},
        {name:'오즈 (Odds)',desc:'액션으로 인해 자신이 걸어야 할 금액 대 이익의 비율'},
        {name:'코인 플립 (Coin Flip)',desc:'2명이 서로 승률이 거의 50:50인 상황 (예: AK vs QQ)'},
        {name:'팟 커밋 (Pot Committed)',desc:'팟에 크게 투자해서 폴드를 포기할 수 없는 상태'},
        {name:'스퀴즈 (Squeeze)',desc:'오픈 레이즈와 콜러 뒤에서 큰 3-벳을 하는 플레이'},
        {name:'아이솔레이션 (Isolation)',desc:'림프한 상대를 레이즈해서 헤즈업으로 만드는 플레이'},
        {name:'매니악 (Maniac)',desc:'거의 모든 핸드를 초공격적으로 플레이하는 사람. LAG의 극단적 형태'},
        {name:'엣지 (Edge)',desc:'상대보다 가진 우위/이점. 스킬 엣지 = 실력 차이에서 오는 장기적 수익'},
        {name:'그라인딩 (Grinding)',desc:'큰 리스크 없이 꾸준히 오래 플레이하며 수익을 쌓는 것'},
        {name:'백도어 (Backdoor)',desc:'턴과 리버 2장이 모두 필요한 드로우. 확률은 낮지만 추가 에퀴티로 작용'},
        {name:'플로팅 (Floating)',desc:'상대 C-bet을 약한 핸드로 콜한 뒤 다음 스트릿에서 블러프로 팟을 가져오는 플레이'},
        {name:'쿨러 (Cooler)',desc:'양쪽 다 강한 핸드라 폴드가 불가능한데 한쪽이 질 수밖에 없는 상황'},
        {name:'익스플로잇 (Exploit)',desc:'상대의 약점을 파악해 GTO에서 벗어나 최대 이득을 취하는 전략'},
        {name:'찹 (Chop)',desc:'팟을 나누거나 블라인드를 회수하는 것. 토너먼트에서는 상금 분배 합의'},
    ];

