    // ============ SHARED DATA ============
    const RANKS = ['A','K','Q','J','T','9','8','7','6','5','4','3','2'];
    const SUITS = [{s:'♠',c:'black'},{s:'♥',c:'red'},{s:'♦',c:'red'},{s:'♣',c:'black'}];
    const POSITIONS = ['UTG','MP','CO','BTN','SB','BB'];
    const POS_ALIAS = {'utg':'UTG','u':'UTG','mp':'MP','m':'MP','co':'CO','c':'CO','btn':'BTN','b':'BTN','bu':'BTN','sb':'SB','bb':'BB'};

    const OPEN_RANGES = {
        UTG:{raise:['AA','KK','QQ','JJ','TT','AKs','AQs','AJs','ATs','KQs','KJs','QJs','AKo','AQo'],call:['99','88','77','A9s','A8s','A5s','A4s','A3s','A2s','KTs','QTs','JTs','T9s','98s','AJo']},
        MP:{raise:['AA','KK','QQ','JJ','TT','99','AKs','AQs','AJs','ATs','A9s','KQs','KJs','KTs','QJs','QTs','JTs','AKo','AQo','AJo','KQo'],call:['88','77','66','A8s','A7s','A5s','A4s','A3s','A2s','T9s','98s','87s','ATo','KJo']},
        CO:{raise:['AA','KK','QQ','JJ','TT','99','88','77','AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KQs','KJs','KTs','K9s','QJs','QTs','Q9s','JTs','J9s','T9s','98s','87s','AKo','AQo','AJo','ATo','KQo','KJo','QJo'],call:['66','55','76s','65s','KTo','QTo','JTo','A9o']},
        BTN:{raise:['AA','KK','QQ','JJ','TT','99','88','77','66','55','44','AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KQs','KJs','KTs','K9s','K8s','K7s','K6s','K5s','QJs','QTs','Q9s','Q8s','JTs','J9s','J8s','T9s','T8s','98s','97s','87s','86s','76s','75s','65s','64s','54s','AKo','AQo','AJo','ATo','A9o','A8o','A7o','KQo','KJo','KTo','K9o','QJo','QTo','Q9o','JTo','J9o','T9o'],call:['33','22','K4s','K3s','K2s','Q7s','Q6s','J7s','T7s','96s','85s','53s','43s','A6o','A5o','A4o','A3o','A2o','K8o','Q8o','J8o','T8o','98o']},
        SB:{raise:['AA','KK','QQ','JJ','TT','99','88','77','66','AKs','AQs','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KQs','KJs','KTs','K9s','K8s','QJs','QTs','Q9s','JTs','J9s','T9s','98s','87s','76s','AKo','AQo','AJo','ATo','A9o','KQo','KJo','KTo','QJo','QTo','JTo'],call:['55','44','33','K7s','K6s','K5s','Q8s','J8s','T8s','97s','86s','75s','65s','54s','A8o','A7o','K9o','Q9o','J9o','T9o']},
        BB:{raise:['AA','KK','QQ','JJ','TT','99','AKs','AQs','AJs','ATs','KQs','KJs','AKo','AQo'],call:['88','77','66','55','44','33','22','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KTs','K9s','K8s','K7s','K6s','K5s','QJs','QTs','Q9s','Q8s','Q7s','JTs','J9s','J8s','J7s','T9s','T8s','T7s','98s','97s','96s','87s','86s','76s','75s','65s','64s','54s','53s','43s','AJo','ATo','A9o','A8o','A7o','A6o','A5o','A4o','A3o','A2o','KQo','KJo','KTo','K9o','K8o','QJo','QTo','Q9o','JTo','J9o','T9o','98o','87o']}
    };
    const VS_RAISE = {
        UTG:{raise:['AA','KK','QQ','AKs'],call:['JJ','TT','99','AQs','AJs','AKo','KQs']},
        MP:{raise:['AA','KK','QQ','AKs','AKo'],call:['JJ','TT','99','88','AQs','AJs','ATs','KQs','AQo']},
        CO:{raise:['AA','KK','QQ','JJ','AKs','AKo','AQs'],call:['TT','99','88','77','AJs','ATs','KQs','KJs','QJs','AQo','AJo','KQo']},
        BTN:{raise:['AA','KK','QQ','JJ','TT','AKs','AQs','AKo'],call:['99','88','77','66','AJs','ATs','A9s','A5s','KQs','KJs','KTs','QJs','QTs','JTs','T9s','98s','AQo','AJo','KQo','KJo']},
        SB:{raise:['AA','KK','QQ','JJ','AKs','AQs','AKo'],call:['TT','99','88','77','AJs','ATs','KQs','KJs','QJs','JTs','AQo','AJo','KQo']},
        BB:{raise:['AA','KK','QQ','JJ','TT','AKs','AQs','AKo'],call:['99','88','77','66','55','44','33','22','AJs','ATs','A9s','A8s','A7s','A6s','A5s','A4s','A3s','A2s','KQs','KJs','KTs','K9s','QJs','QTs','Q9s','JTs','J9s','T9s','98s','87s','76s','65s','AQo','AJo','ATo','KQo','KJo','QJo','JTo']}
    };

    const HAND_RANKINGS = [
        'Royal Flush','Straight Flush','Four of a Kind','Full House','Flush',
        'Straight','Three of a Kind','Two Pair','One Pair','High Card'
    ];

    const GLOSSARY = [
        {name:'올인 (All-in)',desc:'가진 칩 전부를 베팅하는 것'},
        {name:'앤티 (Ante)',desc:'모든 플레이어가 매 핸드 시작 전에 내는 강제 베팅 (토너먼트)'},
        {name:'아웃츠 (Outs)',desc:'내 핸드를 이길 수 있는 핸드로 만들어줄 남은 카드 수'},
        {name:'오픈 (Open)',desc:'누구도 베팅하지 않은 상태에서 첫 레이즈'},
        {name:'오버카드 (Overcard)',desc:'보드의 가장 높은 카드보다 높은 내 홀카드'},
        {name:'오프수트 (Offsuit)',desc:'두 카드의 무늬가 다른 것'},
        {name:'벨류벳 (Value Bet)',desc:'상대가 약한 핸드로 콜해줄 것을 기대하고 하는 베팅'},
        {name:'바이인 (Buy-in)',desc:'게임에 참가하기 위해 필요한 금액'},
        {name:'뱅크롤 (Bankroll)',desc:'포커에 사용할 수 있는 총 자금'},
        {name:'버튼 (Button)',desc:'딜러 위치. 프리플랍 마지막 행동, 플랍 이후 마지막 행동'},
        {name:'블라인드 (Blind)',desc:'강제 베팅. SB와 BB가 카드 받기 전에 냄'},
        {name:'블러프 (Bluff)',desc:'약한 핸드로 강한 척 베팅해서 상대를 폴드시키는 것'},
        {name:'블로커 (Blocker)',desc:'상대가 특정 핸드를 가질 확률을 줄이는 내 카드'},
        {name:'보드 (Board)',desc:'테이블에 깔린 커뮤니티 카드 (플랍+턴+리버)'},
        {name:'브로드웨이 (Broadway)',desc:'T, J, Q, K, A 카드. 또는 이들로 만든 스트레이트'},
        {name:'셋 (Set)',desc:'포켓 페어 + 보드 1장으로 만든 트리플'},
        {name:'셋마이닝 (Set Mining)',desc:'셋을 맞추기 위해 포켓 페어로 콜하는 전략'},
        {name:'세미블러프 (Semi-bluff)',desc:'드로우가 있는 상태에서 블러프 베팅 (맞으면 이기고, 상대 폴드시켜도 이김)'},
        {name:'수티드 (Suited)',desc:'두 카드의 무늬가 같은 것'},
        {name:'수티드 커넥터 (Suited Connector)',desc:'같은 무늬의 연속된 카드 (예: 8♥9♥)'},
        {name:'스트래들 (Straddle)',desc:'BB 왼쪽 자리가 자발적으로 2BB를 내는 블라인드 형태의 베팅'},
        {name:'스택 (Stack)',desc:'내가 가진 칩의 총량'},
        {name:'스틸 (Steal)',desc:'블라인드를 뺏기 위한 레이트 포지션 레이즈'},
        {name:'슬로우플레이 (Slowplay)',desc:'강한 핸드를 가지고 약하게 플레이해 상대를 낚는 것'},
        {name:'C-bet (컨티뉴에이션 벳)',desc:'프리플랍 레이저가 플랍에서도 이어서 베팅하는 것'},
        {name:'체크레이즈 (Check-raise)',desc:'먼저 체크한 뒤 상대가 베팅하면 레이즈하는 것'},
        {name:'커넥터 (Connector)',desc:'연속된 숫자의 두 카드 (예: 78, JT)'},
        {name:'콜드콜 (Cold Call)',desc:'레이즈와 리레이즈가 있는 상황에서 처음 참여하며 콜'},
        {name:'킥커 (Kicker)',desc:'같은 페어일 때 승부를 결정하는 나머지 카드'},
        {name:'타이트 (Tight)',desc:'적은 수의 핸드만 플레이하는 스타일'},
        {name:'턴 (Turn)',desc:'네 번째 커뮤니티 카드'},
        {name:'텔 (Tell)',desc:'상대의 핸드를 추측할 수 있게 해주는 행동/습관'},
        {name:'틸트 (Tilt)',desc:'감정적으로 흔들려 비이성적인 플레이를 하는 것'},
        {name:'트리플 (Three of a Kind)',desc:'같은 숫자 3장'},
        {name:'드로우 (Draw)',desc:'아직 완성되지 않았지만 카드 한두 장으로 완성 가능한 핸드'},
        {name:'도미네이트 (Dominate)',desc:'상대 핸드와 카드 하나가 겹치면서 키커가 앞서는 상황 (예: AK vs AJ)'},
        {name:'넛츠 (Nuts)',desc:'현재 보드에서 가능한 최강 핸드'},
        {name:'니트 (Nit)',desc:'극도로 타이트한 플레이어'},
        {name:'GTO',desc:'Game Theory Optimal. 상대가 어떻게 플레이하든 착취당하지 않는 전략'},
        {name:'ICM',desc:'Independent Chip Model. 토너먼트에서 칩의 실제 가치를 계산하는 모델'},
        {name:'팟 (Pot)',desc:'현재 핸드에 베팅된 총 금액'},
        {name:'팟 오즈 (Pot Odds)',desc:'콜 비용 대비 팟 크기의 비율. 콜의 수학적 가치 판단'},
        {name:'포지션 (Position)',desc:'행동 순서에서의 위치. 뒤에서 행동할수록 유리'},
        {name:'프리미엄 핸드 (Premium)',desc:'AA, KK, QQ, AK 등 최상위 핸드'},
        {name:'프리플랍 (Preflop)',desc:'홀카드 2장만 받은 첫 베팅 라운드'},
        {name:'플랍 (Flop)',desc:'커뮤니티 카드 3장이 동시에 깔리는 두 번째 라운드'},
        {name:'플러시 드로우 (Flush Draw)',desc:'같은 무늬 4장이 있어서 1장 더 오면 플러시 완성'},
        {name:'폴드 에퀴티 (Fold Equity)',desc:'베팅으로 상대를 폴드시킬 수 있는 추가 가치'},
        {name:'핏 오어 폴드 (Fit or Fold)',desc:'플랍에서 맞으면 계속, 안 맞으면 포기하는 전략'},
        {name:'핸드 레인지 (Hand Range)',desc:'특정 상황에서 플레이할 수 있는 핸드의 범위'},
        {name:'홀카드 (Hole Cards)',desc:'나만 볼 수 있는 2장의 카드'},
        {name:'EV (Expected Value)',desc:'기대값. 장기적으로 특정 플레이의 평균 수익/손실'},
        {name:'3-벳 (3-bet)',desc:'상대 레이즈에 대한 리레이즈'},
        {name:'4-벳 (4-bet)',desc:'3-벳에 대한 리레이즈'},
        {name:'림프 (Limp)',desc:'프리플랍에서 레이즈 없이 빅블라인드만 콜하는 것'},
        {name:'리버 (River)',desc:'다섯 번째이자 마지막 커뮤니티 카드'},
        {name:'리버스 임플라이드 오즈',desc:'내 드로우가 완성되어도 상대가 더 좋은 핸드를 가진 경우 잃을 추가 금액'},
        {name:'루즈 (Loose)',desc:'많은 핸드를 플레이하는 스타일'},
        {name:'랙 (Lag)',desc:'Loose-Aggressive. 넓은 범위를 공격적으로 플레이'},
        {name:'임플라이드 오즈 (Implied Odds)',desc:'현재 팟 + 앞으로 더 딸 수 있는 금액을 포함한 오즈'},
        {name:'에퀴티 (Equity)',desc:'현재 핸드가 팟에서 차지하는 기대 지분'},
        {name:'오버벳 (Overbet)',desc:'팟보다 큰 금액을 베팅하는 것'},
        {name:'언더벳 (Underbet)',desc:'팟 대비 매우 작은 금액을 베팅하는 것'},
        {name:'배럴 (Barrel)',desc:'연속적인 베팅. 더블배럴 = 플랍+턴 베팅, 트리플배럴 = 플랍+턴+리버 베팅'},
        {name:'팟 컨트롤 (Pot Control)',desc:'중간 강도 핸드로 팟이 너무 커지지 않게 조절하는 것'},
        {name:'멀티웨이 (Multiway)',desc:'3명 이상의 플레이어가 팟에 참여한 상황'},
        {name:'헤즈업 (Heads-up)',desc:'두 명만 남은 상황'},
        {name:'레귤러 (Regular)',desc:'그 스테이크에서 주로 플레이하는 숙련 플레이어'},
        {name:'피쉬 (Fish)',desc:'실력이 부족한 플레이어 (비하 표현)'},
        {name:'분산 (Variance)',desc:'단기적 운의 영향. 실력과 무관한 결과 변동'},
        {name:'거트샷 (Gutshot)',desc:'가운데 한 장이 필요한 스트레이트 드로우 (아웃츠 4개)'},
        {name:'오픈엔드 (Open-ended)',desc:'양쪽 끝 카드로 완성 가능한 스트레이트 드로우 (아웃츠 8개)'},
        {name:'트립스 (Trips)',desc:'보드 페어 + 핸드 1장으로 만든 트리플 (셋과 구분)'},
        {name:'동크 벳 (Donk Bet)',desc:'오리지널 레이저가 아닌 플레이어가 먼저 베팅하는 것'},
        {name:'쇼다운 (Showdown)',desc:'리버 액션 까지 끝나고 핸드를 공개해 승자를 가리는 것'},
        {name:'드로잉 데드 (Drawing Dead)',desc:'어떤 카드가 와도 이길 수 없는 상태'},
        {name:'히어로 콜 (Hero Call)',desc:'비이성적 약한 핸드로 상대방의 블러프를 잡아내는 콜'},
        {name:'오리지널 (Original)',desc:'프리플랍에서 베팅을 먼저 했던 플레이어'},
        {name:'머크 (Muck)',desc:'카드를 보여주지 않고 폴드하는 것. 쇼다운에서 핸드를 공개하지 않고 포기'},
        {name:'프리즈 아웃 (Freeze Out)',desc:'한번 아웃되면 재참가가 불가능한 토너먼트 형식'},
        {name:'TPTK (Top Pair Top Kicker)',desc:'보드 최고 카드와 페어 + 최고 키커 (예: AK으로 K 보드에서)'},
        {name:'VPIP',desc:'Voluntarily Put Money In Pot. 자발적으로 팟에 참여하는 비율'},
        {name:'패시브 플레이어 (Passive Player)',desc:'콜 위주의 수비적인 플레이를 하는 사람'},
        {name:'어그레시브 플레이어 (Aggressive Player)',desc:'베팅과 레이즈 위주의 공격적 플레이를 하는 사람'},
        {name:'버블 (Bubble)',desc:'토너먼트에서 상금권 직전의 등수 자리'},
        {name:'애드온 (Add-on)',desc:'토너먼트에서 추가로 더 많은 칩을 사기'},
        {name:'오즈 (Odds)',desc:'액션으로 인해 자신이 걸어야 할 금액 대 이익의 비율'},
        {name:'코인 플립 (Coin Flip)',desc:'2명이 서로 승률이 거의 50:50인 상황 (예: AK vs QQ)'},
        {name:'팟 커밋 (Pot Committed)',desc:'팟에 크게 투자해서 폴드를 포기할 수 없는 상태'},
        {name:'스퀴즈 (Squeeze)',desc:'오픈 레이즈와 콜러 뒤에서 큰 3-벳을 하는 플레이'},
        {name:'아이솔레이션 (Isolation)',desc:'림프한 상대를 레이즈해서 헤즈업으로 만드는 플레이'},
        {name:'매니악 (Maniac)',desc:'거의 모든 핸드를 초공격적으로 플레이하는 사람. LAG의 극단적 형태'},
        {name:'엣지 (Edge)',desc:'상대보다 가진 우위/이점. 스킬 엣지 = 실력 차이에서 오는 장기적 수익'},
        {name:'그라인딩 (Grinding)',desc:'큰 리스크 없이 꾸준히 오래 플레이하며 수익을 쌓는 것'},
        {name:'백도어 (Backdoor)',desc:'턴과 리버 2장이 모두 필요한 드로우. 확률은 낮지만 추가 에퀴티로 작용'},
        {name:'플로팅 (Floating)',desc:'상대 C-bet을 약한 핸드로 콜한 뒤 다음 스트릿에서 블러프로 팟을 가져오는 플레이'},
        {name:'쿨러 (Cooler)',desc:'양쪽 다 강한 핸드라 폴드가 불가능한데 한쪽이 질 수밖에 없는 상황'},
        {name:'익스플로잇 (Exploit)',desc:'상대의 약점을 파악해 GTO에서 벗어나 최대 이득을 취하는 전략'},
        {name:'찹 (Chop)',desc:'팟을 나누거나 블라인드를 회수하는 것. 토너먼트에서는 상금 분배 합의'},
    ];

    const PSYC_QUIZ = [
        // Chapter 1
        {q:'Which psychological perspective identifies aspects of behaviour that are the result of evolutionary adaptations?',a:'Evolutionary Perspective',d:['Cognitive Perspective','Developmental Perspective','Clinical Perspective']},
        {q:'Which perspective studies the biological underpinnings of how we think, act, and behave?',a:'Biological-neuroscience Perspective',d:['Emotional Perspective','Social Perspective','Personality Perspective']},
        {q:'Which perspective examines how people change physically, cognitively, socially and emotionally as they age?',a:'Developmental Perspective',d:['Personality Perspective','Cognitive Perspective','Clinical Perspective']},
        {q:'Which perspective seeks to understand aspects of behaviour that are relatively stable over time and situation?',a:'Personality Perspective',d:['Social Perspective','Developmental Perspective','Cultural Perspective']},
        {q:'Which perspective focuses on the causes and treatments of psychological disorders?',a:'Clinical Perspective',d:['Biological-neuroscience Perspective','Emotional Perspective','Cognitive Perspective']},
        {q:'What is pseudoscience?',a:'A collection of beliefs mistakenly thought to be based on valid science',d:['A branch of psychology that studies the brain','Research published in peer-reviewed journals','A method for testing hypotheses']},
        {q:'What does "empirical" mean?',a:'Based on astute observation and accurate measurement',d:['Based on personal intuition','Based on theoretical reasoning alone','Based on popular consensus']},
        {q:'What is critical thinking?',a:'Purposeful, reasoned, goal-directed thinking that seeks to examine, evaluate, solve, and make decisions',d:['Thinking negatively about others\' ideas','Only accepting information from authority figures','Relying on intuition over evidence']},
        {q:'In the nature vs. nurture debate, what does "nature" refer to?',a:'Innate, biological forces',d:['Culture, education, and surroundings','Childhood experiences','Social learning']},
        {q:'What are the 3 components of happiness according to positive psychology?',a:'Positive emotion/pleasure, engagement with life, and living a meaningful life',d:['Money, fame, and power','Health, relationships, and career','Intelligence, creativity, and resilience']},
        {q:'What is a growth mindset?',a:'Believing that human personality and behaviour can change through effort and goal-setting',d:['Believing intelligence is fixed at birth','Focusing only on natural talent','Avoiding challenges to protect self-esteem']},
        {q:'One of the strongest predictors of depression in adolescents is:',a:'Breakups of romantic relationships',d:['Poor grades','Lack of sleep','Social media use']},
        {q:'The cognitive perspective studies:',a:'Mental processes that underlie perception, thought, learning, memory, language, and creativity',d:['How people change as they age','The biological basis of behaviour','How culture affects preferences']},
        {q:'What did the Little Albert study lead to in terms of ethics?',a:'Studies that trigger strong fear responses would never be approved',d:['All psychology research was banned','Only adult participants could be studied','Animal testing became mandatory']},
        {q:'What is open science?',a:'Practices that emphasize transparency of research so findings can be easily shared and tested',d:['Making all research free to read','Publishing only positive results','Allowing the public to design studies']},

        // Chapter 2
        {q:'What is the scientific method?',a:'Basing confidence in an idea on systematic, direct observations by setting up research studies',d:['Forming conclusions based on intuition','Relying on authority figures for knowledge','Making decisions based on personal experience']},
        {q:'What is the theory-data cycle?',a:'When scientists collect data that can either confirm or disconfirm a theory',d:['A method of teaching psychology','The process of publishing a paper','A type of statistical test']},
        {q:'What is replication in research?',a:'Conducting a study more than once on a new sample and finding the same basic results',d:['Copying another researcher\'s paper','Using the same participants twice','Publishing in multiple journals']},
        {q:'What is a variable?',a:'Something of interest that can vary from person to person or situation to situation',d:['A fixed constant in an experiment','A type of research method','The conclusion of a study']},
        {q:'What is the difference between measured and manipulated variables?',a:'Measured variables are observed and recorded; manipulated variables are controlled by assigning participants to different levels',d:['Measured variables are in experiments; manipulated are in surveys','There is no difference','Measured are qualitative; manipulated are quantitative']},
        {q:'What does operationalizing a measured variable mean?',a:'Turning a variable into a number so researchers can statistically analyze the data',d:['Removing a variable from the study','Making a variable unmeasurable','Defining a variable in everyday language']},
        {q:'What are the 3 types of research methods?',a:'Descriptive, correlational, and experimental',d:['Qualitative, quantitative, and mixed','Observational, survey, and clinical','Primary, secondary, and tertiary']},
        {q:'What is random sampling?',a:'A way of choosing participants so everyone in the population of interest has an equal chance of being selected',d:['Assigning participants to groups randomly','Choosing participants who volunteer','Selecting only those who meet specific criteria']},
        {q:'What is naturalistic observation?',a:'Observing behaviour of animals or people in their normal, everyday environments without interfering',d:['Observing people in a laboratory','Asking participants to describe their behaviour','Manipulating variables to see effects']},
        {q:'What is a case study?',a:'An in-depth examination of one person\'s experience, abilities, and behaviour',d:['A study with thousands of participants','A correlational study with two variables','An experiment with a control group']},
        {q:'What can correlational research tell us?',a:'How two or more variables relate to one another',d:['That one variable causes another','Which variable is more important','How to manipulate variables']},
        {q:'"Correlation is not causation" means:',a:'Just because two variables are related does not mean one causes the other',d:['Correlations are never useful','All correlations are weak','Correlational studies are invalid']},
        {q:'In experimental research, what is the independent variable?',a:'The manipulated variable',d:['The measured variable','The confounding variable','The control variable']},
        {q:'In experimental research, what is the dependent variable?',a:'The measured variable',d:['The manipulated variable','The variable held constant','The variable that is eliminated']},
        {q:'What is random assignment?',a:'Using a random method to decide which participants will be in which group',d:['Choosing who gets into the study','Letting participants pick their own group','Assigning all participants to the same group']},
        {q:'What is a placebo condition?',a:'A group told they were going to be experimented on, but weren\'t',d:['The group that receives the real treatment','A group that drops out of the study','The control group that knows it\'s the control']},
        {q:'What is construct validity?',a:'How accurately the operationalizations used in a study capture the variables of interest',d:['Whether results can be generalized to the population','Whether alternative explanations can be ruled out','Whether the study was conducted ethically']},
        {q:'What is external validity?',a:'When the sample of the study can be generalized to the population of interest',d:['How well variables were operationalized','Whether confounds were eliminated','Whether the study can rule out alternative explanations']},
        {q:'What is internal validity?',a:'If a study can rule out alternative explanations for a relationship between two variables',d:['Whether the study can be generalized','How accurately variables were measured','Whether the study was replicated']},
        {q:'What is a confound?',a:'When experimental groups accidentally differ on more than just the independent variable',d:['A type of descriptive statistic','A variable that is intentionally held constant','A successful replication of results']},
        {q:'What is the null hypothesis?',a:'A statistical assumption that there is no effect, no difference, or no relationship between variables',d:['The hypothesis that the researcher wants to prove','A hypothesis based on previous research','The opposite of the control group']},
        {q:'A result is statistically significant when:',a:'p < 0.05, meaning the data are unlikely to occur under the null hypothesis',d:['p > 0.05, meaning the results are important','The sample size is over 1000','The effect size is large']},
        {q:'What is HARKing?',a:'Hypothesizing after the results are known — making it look like you predicted the result',d:['A method of random assignment','A way to increase sample size','A type of descriptive statistic']},
        {q:'What is p-hacking?',a:'Trying many different approaches to find a p-value just under 0.05',d:['Using computers to analyze data faster','A method of ensuring valid results','A way of increasing reliability']},
        {q:'The three ethical principles for IRB decisions are:',a:'Autonomy, beneficence, and justice',d:['Honesty, accuracy, and objectivity','Validity, reliability, and generalizability','Replacement, refinement, and reduction']},
        {q:'What is informed consent?',a:'An application of autonomy, including explaining risks and benefits to participants',d:['Getting permission from the IRB','Publishing results in a journal','Debriefing participants after the study']},
        {q:'The "three Rs" of animal research ethics are:',a:'Replacement, refinement, and reduction',d:['Reliability, replication, and randomization','Rights, respect, and responsibility','Research, review, and reporting']},
        {q:'What is a meta-analysis?',a:'A quantitative estimate of the size of the effect found across a body of research',d:['A single study with many participants','An analysis of qualitative data','A review of one researcher\'s work']},
        {q:'Random sampling determines ___, while random assignment determines ___.', a:'Who gets into the study; who goes where in the study',d:['Who is in the control group; who is in the experimental group','The sample size; the effect size','The independent variable; the dependent variable']},
        {q:'What is standard deviation?',a:'A statistic that calculates how much a batch of scores varies around its mean',d:['The most common score in a group','The middle score in a distribution','The difference between highest and lowest scores']},

        // Chapter 15
        {q:'What is social psychology?',a:'The study of how social context and broader cultural environments influence people\'s thoughts, feelings, and actions',d:['The study of individual personality traits','The study of brain structure','The study of childhood development']},
        {q:'What are schemas?',a:'Mental impressions that organize associated pieces of information we know, like a folder',d:['Experimental research designs','Statistical analyses of data','Types of psychological disorders']},
        {q:'What is transference?',a:'Assuming a new person shares traits with someone familiar, often just because they resemble them',d:['Transferring knowledge from one subject to another','Moving memories from short-term to long-term storage','Changing one\'s attitude after persuasion']},
        {q:'What is the false consensus effect?',a:'Overestimating the extent to which other people\'s beliefs and attitudes are similar to our own',d:['When a group reaches agreement too quickly','Believing that false information is true','When everyone in a group disagrees']},
        {q:'What is the fundamental attribution error?',a:'Defaulting to assume others\' behaviour reflects their personality rather than situational factors',d:['Blaming external factors for our own failures','Accurately identifying the cause of behaviour','Attributing our successes to luck']},
        {q:'What are self-serving attributions?',a:'Interpreting our outcomes in whatever way flatters us most — blaming external factors for failures, crediting ourselves for successes',d:['Always blaming ourselves for bad outcomes','Giving credit to others for our success','Attributing all outcomes to luck']},
        {q:'An attitude has three components:',a:'Affective feeling, cognitive belief, and behavioral motivation',d:['Knowledge, skill, and practice','Past, present, and future','Biological, social, and cultural']},
        {q:'What are implicit attitudes?',a:'Automatic, unconscious associations built up through repeated exposure that are hard to change',d:['Attitudes we can openly state','Attitudes that change easily through reasoning','Attitudes we develop in childhood only']},
        {q:'In the Elaboration Likelihood Model, the central route involves:',a:'Weighing evidence carefully and thoughtful, reflective processing',d:['Being swayed by surface-level cues like looks or brand','Automatic, shallow processing','Changing behaviour without changing attitudes']},
        {q:'In the Elaboration Likelihood Model, the peripheral route involves:',a:'Hollow, automatic processing swayed by surface-level cues rather than substance',d:['Carefully analyzing the strength of arguments','Deep, thoughtful evaluation of evidence','Rational decision-making based on facts']},
        {q:'What is the door-in-the-face compliance strategy?',a:'Start with a huge request, get rejected, then ask for something smaller',d:['Start with a small request, then escalate','Show that many others have done it','Create artificial scarcity']},
        {q:'What is the foot-in-the-door compliance strategy?',a:'Start with a tiny, easy request — once someone complies, they\'re more likely to agree to a bigger ask later',d:['Start with a large request and then reduce it','Use authority to force compliance','Appeal to emotions rather than logic']},
        {q:'What is cognitive dissonance?',a:'When people behave in ways that are out of line with their beliefs, values, or attitudes',d:['When two people disagree on a topic','A type of memory failure','When groups make bad decisions']},
        {q:'What is informational social influence?',a:'Conforming to others\' actions or beliefs to behave correctly or gain an accurate understanding of the world',d:['Conforming just to fit in and avoid rejection','Following orders from authority','Changing attitudes through persuasion']},
        {q:'What is normative social influence?',a:'Conforming not because we think others are right, but simply to fit in and avoid rejection',d:['Conforming because we believe others have better information','Following ethical guidelines','Changing behaviour due to rewards']},
        {q:'What is social facilitation?',a:'The presence of others boosts performance on easy/well-learned tasks but impairs performance on difficult tasks',d:['Groups always perform better than individuals','People work harder when being watched','Performance is always worse in groups']},
        {q:'What is social loafing?',a:'Expending less effort on a task when doing it with others rather than alone',d:['Working harder in a group setting','Leading a group project effectively','Failing to help in an emergency']},
        {q:'What is group polarization?',a:'A tendency for attitudes to become more extreme after discussing with like-minded others',d:['A group splitting into two opposing sides','When groups reach compromise','When group members become more moderate']},
        {q:'What is groupthink?',a:'When people go along with the group instead of speaking up, prioritizing fitting in over thinking critically',d:['When a group makes the best possible decision','When everyone in a group thinks independently','When groups disagree and cannot reach consensus']},
        {q:'In Milgram\'s obedience experiment:',a:'Most people obeyed, but 35% refused',d:['Nobody obeyed the authority','Everyone refused to continue','Only psychopaths obeyed']},
        {q:'What is the bystander effect?',a:'People are less likely to help a victim when other observers are present than when they are alone',d:['People always help when they see an emergency','Groups respond faster than individuals','Bystanders are more helpful than those directly involved']},
        {q:'What is diffusion of responsibility?',a:'In a group, everyone assumes someone else will help, so nobody does',d:['Sharing tasks equally among group members','When leaders delegate authority','Taking personal responsibility for group outcomes']},
        {q:'What is pluralistic ignorance?',a:'Everyone looks at each other, sees no reaction, and concludes there\'s no problem — even if everyone is privately concerned',d:['When everyone in a group is truly unconcerned','A form of deliberate ignorance','When one person ignores the group']},
        {q:'What is prejudice?',a:'A negative attitude toward a group or its members that can lead to discrimination',d:['Treating people differently based on group membership','A positive bias toward one\'s own group','An accurate assessment of group differences']},
        {q:'What is the contact hypothesis?',a:'Prejudice can be reduced when members of different groups interact under the right conditions as equals toward a common goal',d:['Contact between groups always increases prejudice','People should avoid contact with outgroups','Prejudice is entirely eliminated through laws']},
        {q:'The three main factors driving attraction and relationship formation are:',a:'Proximity, mere exposure, and similarity',d:['Intelligence, attractiveness, and wealth','Opposites attract, mystery, and challenge','Age, education, and career']},
        {q:'What is mere exposure in the context of attraction?',a:'Simply seeing someone repeatedly makes us like them more',d:['Being exposed to danger together','Sharing personal information early','Meeting someone through mutual friends']},
        {q:'What is the scarcity principle?',a:'Limited availability makes things more desirable',d:['People want what is cheapest','Abundance increases value','Common items are most attractive']},
        {q:'What is deindividuation?',a:'Losing sight of our own individuality and solely copying others',d:['Developing a unique identity','Standing out from the crowd','Maintaining personal values in a group']},
        {q:'Social identity theory states that:',a:'People maintain a positive attitude for their ingroup by seeing outgroups in a more negative light',d:['Everyone has equal attitudes toward all groups','Outgroups are always viewed positively','Identity is solely determined by individual traits']},
    ];


